#ifndef BLENDSHAPEKEY_H
#define BLENDSHAPEKEY_H

#include <QString>
#include <QHash>

enum class BlendshapeKey {
	BROWOUTERUP_L,
	BROWINNERUP_L,
	BROWDOWN_L,
	EYEBLINK_L,
	EYESQUINT_L,
	EYEWIDE_L,
	EYELOOKUP_L,
	EYELOOKOUT_L,
	EYELOOKIN_L,
	EYELOOKDOWN_L,
	NOSESNEER_L,
	MOUTHUPPERUP_L,
	MOUTHSMILE_L,
	MOUTHLEFT,
	MOUTHFROWN_L,
	MOUTHLOWERDOWN_L,
	JAWLEFT,
	CHEEKPUFF,
	MOUTHSHRUGUPPER,
	MOUTHFUNNEL,
	MOUTHROLLLOWER,
	JAWOPEN,
	TONGUEOUT,
	MOUTHPUCKER,
	MOUTHROLLUPPER,
	JAWRIGHT,
	MOUTHLOWERDOWN_R,
	MOUTHFROWN_R,
	MOUTHRIGHT,
	MOUTHSMILE_R,
	MOUTHUPPERUP_R,
	NOSESNEER_R,
	EYELOOKDOWN_R,
	EYELOOKIN_R,
	EYELOOKOUT_R,
	EYELOOKUP_R,
	EYEWIDE_R,
	EYESQUINT_R,
	EYEBLINK_R,
	BROWDOWN_R,
	BROWINNERUP_R,
	BROWOUTERUP_R,
	HEADLEFT,
	HEADRIGHT,
	HEADUP,
	HEADDOWN,
	HEADROLLLEFT,
	HEADROLLRIGHT,
	EYEBLINKLEFT,
	EYEBLINKRIGHT,
	UNKNOWN,
};

QString blendshapeKeyToString(BlendshapeKey key);
BlendshapeKey blendshapeKeyFromString(const QString &str);

#endif // BLENDSHAPEKEY_H
