#ifndef BLENDSHAPEKEY_H
#define BLENDSHAPEKEY_H

#include <QString>
#include <QHash>

enum class BlendshapeKey {
	BROWOUTERUP_L = 0,
	BROWINNERUP_L = 1,
	BROWDOWN_L = 2,
	EYEBLINK_L = 3,
	EYESQUINT_L = 4,
	EYEWIDE_L = 5,
	EYELOOKUP_L = 6,
	EYELOOKOUT_L = 7,
	EYELOOKIN_L = 8,
	EYELOOKDOWN_L = 9,
	NOSESNEER_L = 10,
	MOUTHUPPERUP_L = 11,
	MOUTHSMILE_L = 12,
	MOUTHLEFT = 13,
	MOUTHFROWN_L = 14,
	MOUTHLOWERDOWN_L = 15,
	JAWLEFT = 16,
	CHEEKPUFF = 17,
	MOUTHSHRUGUPPER = 18,
	MOUTHFUNNEL = 19,
	MOUTHROLLLOWER = 20,
	JAWOPEN = 21,
	TONGUEOUT = 22,
	MOUTHPUCKER = 23,
	MOUTHROLLUPPER = 24,
	JAWRIGHT = 25,
	MOUTHLOWERDOWN_R = 26,
	MOUTHFROWN_R = 27,
	MOUTHRIGHT = 28,
	MOUTHSMILE_R = 29,
	MOUTHUPPERUP_R = 30,
	NOSESNEER_R = 31,
	EYELOOKDOWN_R = 32,
	EYELOOKIN_R = 33,
	EYELOOKOUT_R = 34,
	EYELOOKUP_R = 35,
	EYEWIDE_R = 36,
	EYESQUINT_R = 37,
	EYEBLINK_R = 38,
	BROWDOWN_R = 39,
	BROWINNERUP_R = 40,
	BROWOUTERUP_R = 41,
	HEADLEFT = 42,
	HEADRIGHT = 43,
	HEADUP = 44,
	HEADDOWN = 45,
	HEADROLLLEFT = 46,
	HEADROLLRIGHT = 47,
	EYEBLINKLEFT = 48,
	EYEBLINKRIGHT = 49,
	UNKNOWN = 50,
	COUNT
};

QString blendshapeKeyToString(BlendshapeKey key);
BlendshapeKey blendshapeKeyFromString(const QString &str);

#endif // BLENDSHAPEKEY_H
