#ifndef BLENDSHAPEKEY_H
#define BLENDSHAPEKEY_H

#include <QString>
#include <QHash>

enum class BlendshapeKey {
	BROWINNERUP = 0,
	BROWINNERUP_L = 1,
	BROWINNERUP_R = 2,
	BROWDOWN_L = 3,
	BROWDOWN_R = 4,
	BROWOUTERUP_L = 5,
	BROWOUTERUP_R = 6,
	CHEEKPUFF = 7,
	CHEEKSQUINTLEFT = 8,
	CHEEKSQUINTRIGHT = 9,
	EYELOOKDOWN_L = 10,
	EYELOOKDOWN_R = 11,
	EYELOOKIN_L = 12,
	EYELOOKIN_R = 13,
	EYELOOKOUT_L = 14,
	EYELOOKOUT_R = 15,
	EYELOOKUP_L = 16,
	EYELOOKUP_R = 17,
	EYEBLINK_L = 18,
	EYEBLINK_R = 19,
	// EYEBLINKLEFT = 20,
	// EYEBLINKRIGHT = 21,
	EYESQUINT_L = 20,
	EYESQUINT_R = 21,
	EYEWIDE_L = 22,
	EYEWIDE_R = 23,
	HEADDOWN = 24,
	HEADLEFT = 25,
	HEADRIGHT = 26,
	HEADROLLLEFT = 27,
	HEADROLLRIGHT = 28,
	HEADUP = 29,
	JAWFORWARD = 30,
	JAWLEFT = 31,
	JAWOPEN = 32,
	JAWRIGHT = 33,
	MOUTHCLOSE = 34,
	MOUTHDIMPLELEFT = 35,
	MOUTHDIMPLERIGHT = 36,
	MOUTHFROWN_L = 37,
	MOUTHFROWN_R = 38,
	MOUTHFUNNEL = 39,
	MOUTHLEFT = 40,
	MOUTHLOWERDOWN_L = 41,
	MOUTHLOWERDOWN_R = 42,
	MOUTHPRESSLEFT = 43,
	MOUTHPRESSRIGHT = 44,
	MOUTHPUCKER = 45,
	MOUTHRIGHT = 46,
	MOUTHROLLLOWER = 47,
	MOUTHROLLUPPER = 48,
	MOUTHSHRUGLOWER = 49,
	MOUTHSHRUGUPPER = 50,
	MOUTHSMILE_L = 51,
	MOUTHSMILE_R = 52,
	MOUTHSTRETCHLEFT = 53,
	MOUTHSTRETCHRIGHT = 54,
	MOUTHUPPERUP_L = 55,
	MOUTHUPPERUP_R = 56,
	NOSESNEER_L = 57,
	NOSESNEER_R = 58,
	TONGUEOUT = 59,
	UNKNOWN = 60,
	COUNT
};

static const std::unordered_map<QString, BlendshapeKey> blendshapeMapping = {
	// vTubeStudio blendshape names
	{"browOuterUp_L", BlendshapeKey::BROWOUTERUP_L},
	{"browInnerUp_L", BlendshapeKey::BROWINNERUP_L},
	{"browDown_L", BlendshapeKey::BROWDOWN_L},
	{"eyeBlink_L", BlendshapeKey::EYEBLINK_L},
	{"eyeSquint_L", BlendshapeKey::EYESQUINT_L},
	{"eyeWide_L", BlendshapeKey::EYEWIDE_L},
	{"eyeLookUp_L", BlendshapeKey::EYELOOKUP_L},
	{"eyeLookOut_L", BlendshapeKey::EYELOOKOUT_L},
	{"eyeLookIn_L", BlendshapeKey::EYELOOKIN_L},
	{"eyeLookDown_L", BlendshapeKey::EYELOOKDOWN_L},
	{"noseSneer_L", BlendshapeKey::NOSESNEER_L},
	{"mouthUpperUp_L", BlendshapeKey::MOUTHUPPERUP_L},
	{"mouthSmile_L", BlendshapeKey::MOUTHSMILE_L},
	{"mouthLeft", BlendshapeKey::MOUTHLEFT},
	{"mouthFrown_L", BlendshapeKey::MOUTHFROWN_L},
	{"mouthLowerDown_L", BlendshapeKey::MOUTHLOWERDOWN_L},
	{"jawLeft", BlendshapeKey::JAWLEFT},
	{"cheekPuff", BlendshapeKey::CHEEKPUFF},
	{"mouthShrugUpper", BlendshapeKey::MOUTHSHRUGUPPER},
	{"mouthFunnel", BlendshapeKey::MOUTHFUNNEL},
	{"mouthRollLower", BlendshapeKey::MOUTHROLLLOWER},
	{"jawOpen", BlendshapeKey::JAWOPEN},
	{"tongueOut", BlendshapeKey::TONGUEOUT},
	{"mouthPucker", BlendshapeKey::MOUTHPUCKER},
	{"mouthRollUpper", BlendshapeKey::MOUTHROLLUPPER},
	{"jawRight", BlendshapeKey::JAWRIGHT},
	{"mouthLowerDown_R", BlendshapeKey::MOUTHLOWERDOWN_R},
	{"mouthFrown_R", BlendshapeKey::MOUTHFROWN_R},
	{"mouthRight", BlendshapeKey::MOUTHRIGHT},
	{"mouthSmile_R", BlendshapeKey::MOUTHSMILE_R},
	{"mouthUpperUp_R", BlendshapeKey::MOUTHUPPERUP_R},
	{"noseSneer_R", BlendshapeKey::NOSESNEER_R},
	{"eyeLookDown_R", BlendshapeKey::EYELOOKDOWN_R},
	{"eyeLookIn_R", BlendshapeKey::EYELOOKIN_R},
	{"eyeLookOut_R", BlendshapeKey::EYELOOKOUT_R},
	{"eyeLookUp_R", BlendshapeKey::EYELOOKUP_R},
	{"eyeWide_R", BlendshapeKey::EYEWIDE_R},
	{"eyeSquint_R", BlendshapeKey::EYESQUINT_R},
	{"eyeBlink_R", BlendshapeKey::EYEBLINK_R},
	{"browDown_R", BlendshapeKey::BROWDOWN_R},
	{"browInnerUp_R", BlendshapeKey::BROWINNERUP_R},
	{"browOuterUp_R", BlendshapeKey::BROWOUTERUP_R},
	{"headLeft", BlendshapeKey::HEADLEFT},
	{"headRight", BlendshapeKey::HEADRIGHT},
	{"headUp", BlendshapeKey::HEADUP},
	{"headDown", BlendshapeKey::HEADDOWN},
	{"headRollLeft", BlendshapeKey::HEADROLLLEFT},
	{"headRollRight", BlendshapeKey::HEADROLLRIGHT},

	//MeowFace blendshape names
	{"browOuterUpLeft", BlendshapeKey::BROWOUTERUP_L},
	{"browInnerUpLeft", BlendshapeKey::BROWINNERUP_L},
	{"browDownLeft", BlendshapeKey::BROWDOWN_L},
	{"eyeBlinkLeft", BlendshapeKey::EYEBLINK_L},
	{"eyeSquintLeft", BlendshapeKey::EYESQUINT_L},
	{"eyeWideLeft", BlendshapeKey::EYEWIDE_L},
	{"eyeLookUpLeft", BlendshapeKey::EYELOOKUP_L},
	{"eyeLookOutLeft", BlendshapeKey::EYELOOKOUT_L},
	{"eyeLookInLeft", BlendshapeKey::EYELOOKIN_L},
	{"eyeLookDownLeft", BlendshapeKey::EYELOOKDOWN_L},
	{"noseSneerLeft", BlendshapeKey::NOSESNEER_L},
	{"mouthUpperUpLeft", BlendshapeKey::MOUTHUPPERUP_L},
	{"mouthSmileLeft", BlendshapeKey::MOUTHSMILE_L},
	{"mouthFrownLeft", BlendshapeKey::MOUTHFROWN_L},
	{"mouthLowerDownLeft", BlendshapeKey::MOUTHLOWERDOWN_L},
	{"mouthLowerDownRight", BlendshapeKey::MOUTHLOWERDOWN_R},
	{"mouthFrownRight", BlendshapeKey::MOUTHFROWN_R},
	{"mouthSmileRight", BlendshapeKey::MOUTHSMILE_R},
	{"mouthUpperUpRight", BlendshapeKey::MOUTHUPPERUP_R},
	{"noseSneerRight", BlendshapeKey::NOSESNEER_R},
	{"eyeLookDownRight", BlendshapeKey::EYELOOKDOWN_R},
	{"eyeLookInRight", BlendshapeKey::EYELOOKIN_R},
	{"eyeLookOutRight", BlendshapeKey::EYELOOKOUT_R},
	{"eyeLookUpRight", BlendshapeKey::EYELOOKUP_R},
	{"eyeWideRight", BlendshapeKey::EYEWIDE_R},
	{"eyeSquintRight", BlendshapeKey::EYESQUINT_R},
	{"eyeBlinkRight", BlendshapeKey::EYEBLINK_R},
	{"browDownRight", BlendshapeKey::BROWDOWN_R},
	{"browInnerUpRight", BlendshapeKey::BROWINNERUP_R},
	{"browOuterUpRight", BlendshapeKey::BROWOUTERUP_R},

	// iOS blendshapes
	{"BrowDownLeft", BlendshapeKey::BROWDOWN_L},
	{"BrowDownRight", BlendshapeKey::BROWDOWN_R},
	{"BrowInnerUp", BlendshapeKey::BROWINNERUP},
	{"BrowOuterUpLeft", BlendshapeKey::BROWOUTERUP_L},
	{"BrowOuterUpRight", BlendshapeKey::BROWOUTERUP_R},
	{"CheekPuff", BlendshapeKey::CHEEKPUFF},
	{"CheekSquintLeft", BlendshapeKey::CHEEKSQUINTLEFT},
	{"CheekSquintRight", BlendshapeKey::CHEEKSQUINTRIGHT},
	{"EyeBlinkLeft", BlendshapeKey::EYEBLINK_L},
	{"EyeBlinkRight", BlendshapeKey::EYEBLINK_R},
	{"EyeLookDownLeft", BlendshapeKey::EYELOOKDOWN_L},
	{"EyeLookDownRight", BlendshapeKey::EYELOOKDOWN_R},
	{"EyeLookInLeft", BlendshapeKey::EYELOOKIN_L},
	{"EyeLookInRight", BlendshapeKey::EYELOOKIN_R},
	{"EyeLookOutLeft", BlendshapeKey::EYELOOKOUT_L},
	{"EyeLookOutRight", BlendshapeKey::EYELOOKOUT_R},
	{"EyeLookUpLeft", BlendshapeKey::EYELOOKUP_L},
	{"EyeLookUpRight", BlendshapeKey::EYELOOKUP_R},
	{"EyeSquintLeft", BlendshapeKey::EYESQUINT_L},
	{"EyeSquintRight", BlendshapeKey::EYESQUINT_R},
	{"EyeWideLeft", BlendshapeKey::EYEWIDE_L},
	{"EyeWideRight", BlendshapeKey::EYEWIDE_R},
	{"JawForward", BlendshapeKey::JAWFORWARD},
	{"JawLeft", BlendshapeKey::JAWLEFT},
	{"JawOpen", BlendshapeKey::JAWOPEN},
	{"JawRight", BlendshapeKey::JAWRIGHT},
	{"MouthClose", BlendshapeKey::MOUTHCLOSE},
	{"MouthDimpleLeft", BlendshapeKey::MOUTHDIMPLELEFT},
	{"MouthDimpleRight", BlendshapeKey::MOUTHDIMPLERIGHT},
	{"MouthFrownLeft", BlendshapeKey::MOUTHFROWN_L},
	{"MouthFrownRight", BlendshapeKey::MOUTHFROWN_R},
	{"MouthFunnel", BlendshapeKey::MOUTHFUNNEL},
	{"MouthLeft", BlendshapeKey::MOUTHLEFT},
	{"MouthLowerDownLeft", BlendshapeKey::MOUTHLOWERDOWN_L},
	{"MouthLowerDownRight", BlendshapeKey::MOUTHLOWERDOWN_R},
	{"MouthPucker", BlendshapeKey::MOUTHPUCKER},
	{"MouthPressLeft", BlendshapeKey::MOUTHPRESSLEFT},
	{"MouthPressRight", BlendshapeKey::MOUTHPRESSRIGHT},
	{"MouthRight", BlendshapeKey::MOUTHRIGHT},
	{"MouthRollLower", BlendshapeKey::MOUTHROLLLOWER},
	{"MouthRollUpper", BlendshapeKey::MOUTHROLLUPPER},
	{"MouthShrugLower", BlendshapeKey::MOUTHSHRUGLOWER},
	{"MouthShrugUpper", BlendshapeKey::MOUTHSHRUGUPPER},
	{"MouthSmileLeft", BlendshapeKey::MOUTHSMILE_L},
	{"MouthSmileRight", BlendshapeKey::MOUTHSMILE_R},
	{"MouthStretchLeft", BlendshapeKey::MOUTHSTRETCHLEFT},
	{"MouthStretchRight", BlendshapeKey::MOUTHSTRETCHRIGHT},
	{"MouthUpperUpLeft", BlendshapeKey::MOUTHUPPERUP_L},
	{"MouthUpperUpRight", BlendshapeKey::MOUTHUPPERUP_R},
	{"NoseSneerLeft", BlendshapeKey::NOSESNEER_L},
	{"NoseSneerRight", BlendshapeKey::NOSESNEER_R},
	{"TongueOut", BlendshapeKey::TONGUEOUT},

};

BlendshapeKey blendshapeKeyFromString(const QString &str);
QString blendshapeKeyToString(BlendshapeKey key);

#endif // BLENDSHAPEKEY_H
